##===- projects/sample/lib/Makefile ------------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS=CUDD Util MemoryModel MSSA WPA DDA MTA STC Instrumentation RC
#PARALLEL_DIRS= SIMD

include $(LEVEL)/Makefile.common
