##===- projects/sample/tools/Makefile ----------------------*- Makefile -*-===##

#
# Relative path to the top of the source tree.
#
LEVEL=..

#
# List all of the subdirectories that we will compile.
#
DIRS= WPA DDA STC Instrumentation MTA RC

include $(LEVEL)/Makefile.common
